### ISSUE TITLE
Holiday macros aren't working...

### ISSUE THREAD

**Issue by stijnb1234** [surfrock66/RPi-RGB-Web#2]
**PHP5 fixed!**

**Comment by stijnb1234** [comment]
**Not fixed yet!**

And I found out that the Christmas light and that sort of things are not working!

Why?

**Comment by surfrock66** [comment]
Which distro are you using?  I'm using Raspbian, and with up to date repos, there's a php5 and not a php7.0.  Are you using an external repository?

I would totally be willing to update the list of packages for other distros, but I can't really test that right now.  I suspect this is related to why the macros aren't working.

**Comment by DeveloperBoy** [comment]
I fixed it already with php7.0, but:

Why does Christmas lighting mode etc. not work?

**Comment by surfrock66** [comment]
Can you tell me a bit more about your setup?  What distro are you running on your pi?  I can't even find php7 in the raspbian repositories.

The next thing is to figure out why the macros aren't working.  The selection puts a value in the text file which is read by the daemon...is the text file getting updated?  If not, it could be a permissions issue.  If it's updating, is the daemon looking in the right location?  If all that is good, you can take RGB.sh and start executing the pigs commands manually to see if they're working.  All of that will give me some clues as to how to help.

**Comment by stijnb1234** [comment]
I have a raspberry pi 2 with the new raspbian version on it.

I have used this tutorial for cabling: [Click on this](http://dordnung.de/raspberrypi-ledstrip/)

I use a normal RGB LED strip.

But my question is now: Why does Christmas lighting etc. not work?

**Comment by surfrock66** [comment]
Can you run this:

cat /etc/issue; cat /etc/debian_version; cat /etc/os-release

I need to figure out what's different on your system than mine other than php.  I still don't have enough info to understand why the holiday macros aren't working.  I suspect it's a problem with /etc/RGB.sh more than a problem with php.  If you can, execute the commands in there manually (for example, does "wget -qO- http://localhost/RGB.txt" work?)  Do any of the effects work (like strobe or party)?

**Comment by DeveloperBoy** [comment]
No. It are 2 problems.

Problem 1 is that with the latest version of Raspbian there is no more PHP.

Problem 2 is that the holiday macro's aren't working.

They have nothing to do with each other.

**Comment by surfrock66** [comment]
I'm trying to help here, but you're giving me nothing to work on.

I tore up my rPi and reinstalled it with the new Raspbian: 

`# cat /etc/issue`
`Raspbian GNU/Linux 9 \n \l`

I also confirmed my php version, installed with "apt-get install php":

`# php -v`
`PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )`
`Copyright (c) 1997-2017 The PHP Group`
`Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies`
`    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies`

My web page is still working fine.  I tested ALL macros:

- Solid Light
- Strobe Light
- Party
- Color Step
- Color Fade
- Christmas Step
- Christmas Fade
- Halloween Step
- Halloween Fade
- 4th of July Step
- 4th of July Fade

All worked normally, including after a reboot.

Do ANY buttons work for you?  Can you include the output of the following:
`# cat /etc/issue`
`# php -v`

The only issue I can confirm/reproduce is a bug in my README where "php5" needs to be "php".  This is my output:

`# apt-get install apache2 php mysql-client mysql-server vsftpd`
`Reading package lists... Done`
`Building dependency tree       `
`Reading state information... Done`
`apache2 is already the newest version (2.4.25-3+deb9u3).`
`mysql-client is already the newest version (5.5.9999+default).`
`mysql-server is already the newest version (5.5.9999+default).`
`php is already the newest version (1:7.0+49).`
`vsftpd is already the newest version (3.0.3-8).`
`0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by stijnb1234** [comment]
**cat /etc/issue =** Raspbian GNU/Linux 9 \n \l

**cat /etc/debian_version =** 9.3

**wget -qO- http://localhost/RGB.txt =**
12-25-Step
0
191
255


**cat /etc/os-release =** PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**php -v =** PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**My LED strip will turn black at:**
- Christmas Step
- Christmas Fade
- Halloween Step
- Halloween Fade
- 4th of July Step
- 4th of July Fade
[Click on me for a picture of the ones who don't work](http://prntscr.com/hwe1ab)

**Comment by surfrock66** [comment]
Real quick, does the "strobe" work for a color?  Do Party/Fade/Step work?

**Comment by stijnb1234** [comment]
They all are working. Also Strobe gives a color. Party, Fade and Step do also work.

**Comment by surfrock66** [comment]
Ok, here's my thinking.

We know the website is updating the file.  You should probably confirm that the contents of /var/www/html/RGB.txt reflect each of the macros, but I'm pretty sure that's working.  We know the daemon running /etc/RGB.sh is working.  We know the GPIO communication through pigs is working.  So, what is different between the holiday macros and the other macros?  Well...nearly nothing.

The whole thing is a big loop, and depending on the contents of /var/www/html/RGB.txt we enter the contents of something similar to a case statement (it's if/elif/else, but the function is the same).  The color values are populated into 3 arrays, one for Red, Blue, and Green, with as many intermediate values as needed.  There's nearly no difference between the holiday macros and the other macros.

To that end, we can simulate one of the macros to figure out where things go wrong.  The simplest would be the Christmas step macro.  Please execute the following code on a shell (assuming you're using the default configuration where red is pin 24, green is pin 25, and blue is pin 22):

`count=0`
`while true; do`
`  stepR=(255 0)`
`  stepG=(0 255)`
`  stepB=(0 0)`
`  k=$(($count%2))`
`  count=$(($count+1))`
`  pigs p 24 ${stepR[$k]} p 25 ${stepG[$k]} p 22 ${stepB[$k]}`
`  sleep 1`
`done`

I want to see if you get any errors, or if you suddenly get a working macro.

**Comment by stijnb1234** [comment]
It works. It goes from red-green-red-green with a change time of 1 second.

So that macro is working. But I can't find any code for the holiday macro's in the RGB.sh file. Does you added the code into the Github file?

**Comment by surfrock66** [comment]
You're totally right, the RGB.sh here is behind, crap!  I just pushed a commit which includes all changes to RGB.sh.

Sorry that took so long, I thought the code here was up to date...when I pushed the RGB.php code with the holiday stuff I assumed the RGB.sh was up to date in my local repo.  Totally my bad!
